name: deleted_service

on:
  delete:
    branches:
      - '*'

jobs:
  check_deleted_branch:
    runs-on: ubuntu-latest
   
    steps:
      - name: Set deleted branch variable
        run: |
          echo ${{github.event.ref}}
    