name: deleted_service

on:
  delete
    

jobs:
  check_deleted_branch:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'feature')
    steps:
      - name: Set deleted branch variable
        run: |
          echo ${{github.event.ref}}
    