name: deleted_service

on:
  delete:
    branches:
      - '*'

jobs:
  check_deleted_branch:
    runs-on: ubuntu-latest
    if: ${{github.event.ref}} == 'feature'*
    steps:
      - name: Set deleted branch variable
        run: |
          echo ${{github.event.ref}}
    