name: deleted_service

on:
  delete:
    branches:
      - '*'

jobs:
  check_deleted_branch:
    runs-on: ubuntu-latest
   
    steps:
      - name: Set deleted branch variable
        run: |
          echo ${{github.event.ref}}
          echo "${{ toJson(github.event) }}" > event.json
          branch=$(sed -n 's/.*ref: \(.*\),/\1/p' event.json)
          echo "DELETED_BRANCH=$branch" >> $GITHUB_ENV

      - name: Check if the deleted branch is a feature branch
        run: |
          if [[ "$DELETED_BRANCH" == 'feature/'* ]]; then
            echo "This is a feature branch."
          else
            echo "This is not a feature branch. Exiting the job."
            exit 78  # Exiting with a neutral status code (78) to indicate skipping the job
          fi

      - name: Your main job steps
        run: |
          # Add your main job steps here for feature branches














#