name: Delete Service from deleted branch

on:
  delete:
    branches:
      - 'feature*'
  # delete:
  #   branches:
  #     - '*'

jobs:
  
  deleted_service:
    runs-on: ubuntu-latest
    if: github.event_name == 'delete'
    env: 
      DELETED_BRANCH: $(echo "${{ toJson(github.event) }}" | sed -n 's/.*"ref":"refs\/heads\/\([^"]*\)".*/\1/p')
 
    steps:
        - name: Run on branch deletion
          id: branch_deletion
          if: github.event_name == 'delete'
          run: |
            echo ${{ github.ref }}
            echo "Branch deleted. Running specific steps for branch deletion."
            echo "blah blah"

        - name: Get Event JSON
          run: |
            echo $DELETED_BRANCH

            echo ${{ steps.branch_deletion.outputs.deleted_service}}
            echo "${{ toJson(github.event) }}" > event.json
      
        - name: Extract Deleted Branch Name
          if: env.DELETED_BRANCH == 'true'
          id: extract_branch
          run: |
            deleted_branch_name=$(sed -n 's/.*ref: \(.*\),/\1/p' event.json)
            echo "Deleted branch name: $deleted_branch_name"
            echo "deleted_branch_name=$deleted_branch_name" >> $GITHUB_ENV
  
        - name: Use Deleted Branch Name
          if: env.DELETED_BRANCH == 'true'
          run: |
            echo "Deleted branch name: $deleted_branch_name"
  
        - name: Use Deleted Branch Name
          if: env.DELETED_BRANCH == 'true'
          run: |
            echo "Deleted branch name from environment: $deleted_branch_name"