name: deleted_service

on:
  delete:
    branches:
      - '*'

jobs:
  check_deleted_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set deleted branch variable
        run: |
          echo "${{ toJson(github.event) }}" > event.json
          branch=$(sed -n 's/.*ref: \(.*\),/\1/p' event.json)
          echo "DELETED_BRANCH=$branch" >> $GITHUB_ENV

      - name: Check if the deleted branch is a feature branch
        run: |
          if [[ "$DELETED_BRANCH" == 'feature/'* ]]; then
            echo "This is a feature branch."
          else
            echo "This is not a feature branch. Exiting the job."
            exit 78  # Exiting with a neutral status code (78) to indicate skipping the job
          fi

      - name: Your main job steps
        run: |
          # Add your main job steps here for feature branches














# name: Delete Service from deleted branch

# on:
#   delete:
#     branches:
#       - 'feature*'
#   # delete:
#   #   branches:
#   #     - '*'

# jobs:
  
#   deleted_service:
#     runs-on: ubuntu-latest
#     if: github.event_name == 'delete'
#     env: 
#       DELETED_BRANCH: $(echo "${{ toJson(github.event) }}" | sed -n 's/.*"ref":"refs\/heads\/\([^"]*\)".*/\1/p')
 
#     steps:
#         - name: Run on branch deletion
#           id: branch_deletion
#           if: github.event_name == 'delete'
#           run: |
#             echo ${{ github.ref }}
#             echo "Branch deleted. Running specific steps for branch deletion."
#             echo "blah blah"
#             json=${{ toJson(github.event) }}
#             echo $json

#             deleted_branch_name1=$(sed -n 's/.*ref: \(.*\),/\1/p' $json)
#             echo "NAME: $deleted_branch_name1"

#         - name: Get Event JSON
#           run: |
            
      
#         - name: Extract Deleted Branch Name
#           id: extract_branch
#           run: |
#             deleted_branch_name=
#             echo "Deleted branch name: $deleted_branch_name"
#             echo "deleted_branch_name=$deleted_branch_name" >> $GITHUB_ENV
  
#         - name: Use Deleted Branch Name
#           run: |
#             echo "Deleted branch name: $deleted_branch_name"
  
#         - name: Use Deleted Branch Name
#           run: |
#             echo "Deleted branch name from environment: $deleted_branch_name"