name: Conditional Workflow

on:
  push:
    branches:
      - '*'
  delete:
    branches:
      - '*'

jobs:
  check_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run if branch is 'main'
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "This code will run only if the branch is 'main'"
          # Your specific steps for the 'main' branch

      - name: Run if branch is not 'main'
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          echo "This code will run for branches other than 'main'"
          # Your specific steps for branches other than 'main'

      - name: Run on branch deletion
        if: github.event_name == 'delete'
        run: |
          echo "Branch deleted. Running specific steps for branch deletion."
          echo "blah blah"
          echo "Branch name is ${GITHUB_REF#refs/heads/}"
          # Your specific steps for branch deletion
      - name: Get Event JSON
        run: echo "${{ toJson(github.event) }}" > event.json

      - name: Extract Deleted Branch Name
        id: extract_branch
        run: |
          deleted_branch_name=$(jq -r '.ref' event.json | sed 's|refs/heads/||')
          echo "Deleted branch name: $deleted_branch_name"
          echo "deleted_branch_name=$deleted_branch_name" >> $GITHUB_ENV

      - name: Use Deleted Branch Name
        run: |
          echo "Deleted branch name from environment: $deleted_branch_name"
          # Add your further steps using $deleted_branch_name